name: mle-dev
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1m
  - pip=21.2.2
  - python=3.8.12
  - setuptools=58.0.4
  - sqlite=3.37.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - cycler==0.11.0
    - fonttools==4.29.1
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - numpy==1.22.2
    - packaging==21.3
    - pandas==1.4.1
    - pillow==9.0.1
    - pyparsing==3.0.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - six==1.16.0
    - threadpoolctl==3.1.0
